name: Automacao Monitoramento de Logs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Executar script
      run: python script_logs.py
